version: '3'

networks:
  whatsapp:
    driver: bridge

services:
  go-whatsapp-multidevice-rest:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'vpnbazar/go-whatsapp-multidevice:latest'
    container_name: 'go-whatsapp-multidevice'
    networks:
      - whatsapp
    ports:
      - 3100:3100
    env_file:
      - ./.env
    volumes:
      - ./dbs:/usr/app/gowam-rest/dbs
    restart: unless-stopped
